### PR TITLE
operator now uses the namespace configured through its inputs.cue

### PR DESCRIPTION
**Pull request by alecholmez**
Signed-off-by: Alec Holmes <alecholmez@me.com>

### CODE REVIEW

**Comment by alecholmez** [comment]
## Testing

### Prerequisites
- A kubernetes cluster with admin privileges
- quay.io credentials

### Deploying
- Make sure your kube context is set to your cluster
- Make a new branch in gitops-core
- Edit `inputs.cue` `operator_namespace` to the `foobar` namespace
- Commit and push
- In the operator code, edit the `pkg/cuemodule/core/k8s/outputs/operator.yaml` statefulset args from the `v0.9.3` tag to your branch.
- Build the container:
```
./scripts/build container
```
- Tag and push:
```
docker tag docker.greymatter.io/internal/gm-operator:latest quay.io/greymatterio/operator:test-namespace
docker push quay.io/greymatterio/operator:test-namespace
```
- Deploy the operator with the following command:
```
(
# CUE config root
cd pkg/cuemodule/core

# Necessary only so we can create the secrets before launching the operator.
# The operator manifests create this namespace if it doesn't already exist.
kubectl create namespace foobar

# Image pull secret
kubectl create secret docker-registry gm-docker-secret \
  --docker-server=quay.io \
  --docker-username=$QUAY_USERNAME \
  --docker-password=$QUAY_PASSWORD \
  -n foobar

# GitOps SSH key
# EDIT THIS to reflect your own, or some other SSH private key with access,
# to the repository you would like the operator to use for GitOps. Note
# that by default, the operator is going to fetch from
# https://github.com/greymatter-io/gitops-core and you would
# need to edit the operator StatefulSet to change the argument to the
# operator binary to change the git repository or branch.
kubectl create secret generic greymatter-sync-secret \
  --from-file=id_ed25519=$HOME/.ssh/id_ed25519 \
  -n foobar

# Operator installation and supporting manifests
cue eval -c ./k8s/outputs --out text \
         -t operator_image=quay.io/greymatterio/operator:test-namespace -t operator_namespace=foobar \
         -e operator_manifests_yaml | kubectl apply -f -
)
```
Note the namespace for deployment.
- Let the cluster come up and then verify the mesh is successfully deployed with:
```
k get svc edge -n greymatter
```
- Access the dashboard from the external-ip from the above command.

**Review by danielpcox — APPROVED** [review]
Worked for me and looks good. Interesting how your test works by injecting a tag. 👍

**Comment by danielpcox** [comment]
Mentioned this in Slack, but if you introduce these changes (except for the removal of auto_apply_mesh) I think it'll fix the spire integration test: https://github.com/greymatter-io/gitops-core/pull/42/commits/f01c52258a1a352bcf75336588dcc9e2a07b319b

**Review by joel-epstein — APPROVED** [review]
I just completed my testing and got a good result deploying the operator into a namespace that was configured via inputs.cue (a namespace called "foobar")

**Comment by joel-epstein** [comment]
I have tested the latest version and I now see the gm-operator-rolebinding deploying the operator to a namespace named 'foobar99.'  The output from the deployment displays as expected:

$ ( cd pkg/cuemodule/core;  kubectl create namespace foobar99;  kubectl create secret docker-registry gm-docker-secret   --docker-server=quay.io   --docker-username=$QUAY_USERNAME   --docker-password=$QUAY_PASSWORD   -n foobar99;  kubectl create secret generic greymatter-sync-secret   --from-file=id_ed25519=$HOME/.ssh/id_ed25519   -n foobar99;  cue eval -c ./k8s/outputs --out text          -t operator_image=quay.io/greymatterio/operator:test-namespace -t operator_namespace=foobar99          -e operator_manifests_yaml | kubectl apply -f -; )
namespace/foobar99 created
secret/gm-docker-secret created
secret/greymatter-sync-secret created
Warning: resource namespaces/foobar99 is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
namespace/foobar99 configured
statefulset.apps/greymatter-operator created
configmap/overrides-cue created
serviceaccount/greymatter-operator created
role.rbac.authorization.k8s.io/gm-leader-election-role created
clusterrole.rbac.authorization.k8s.io/gm-operator-role unchanged
rolebinding.rbac.authorization.k8s.io/gm-leader-election-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/gm-operator-rolebinding unchanged
secret/gm-webhook-cert created
service/gm-webhook created
mutatingwebhookconfiguration.admissionregistration.k8s.io/gm-mutate-config configured
rolebinding.rbac.authorization.k8s.io/gm-leader-election-rolebinding unchanged
clusterrolebinding.rbac.authorization.k8s.io/gm-operator-rolebinding unchanged
secret/gm-webhook-cert unchanged
service/gm-webhook unchanged
mutatingwebhookconfiguration.admissionregistration.k8s.io/gm-mutate-config configured

The Edge node URL and the Dashboard are rendering as expected with low latency.

I am attaching an operator log showing the rolebinding and configured namespace 'foobar99'

RoleBinding_AlternateNamespace

**Review by joel-epstein — APPROVED** [review]
Testing has passed.  See my comment/results in the main conversation.

-Joel

**Pull request merged**
