### PR TITLE
WIP: update resources.patch to allow smaller dev clusters to deploy

### PR DESCRIPTION
**Pull request by joel-epstein**
This PR will allow dev to deploy smaller k8s clusters and not be obstructed by issues associated with the new default requests/limits that are more relevant to a production-ready k8s cluster.

### CODE REVIEW

**Comment by alecholmez** [comment]
@joel-epstein can you hold off on this. We're in the process of reworking all the resource limit stuff.

**Comment by joshuaswickirl** [comment]
https://greymatter.atlassian.net/browse/OPS-26

**Comment by dontlaugh** [comment]
@aries-greymatter Relevant to our discussion today

**Comment by alecholmez** [comment]
This patch is no longer needed so we can close this out.

**Comment by joel-epstein** [comment]
Closing this out as prod-ops has implemented `resource.cue` at the root.

**Pull request closed without merging**
