### PR TITLE
Removing --remote from git submodule update commands

### PR DESCRIPTION
**Pull request by danielpcox**
This command causes all of the submodules of the current repository (recursively) to be updated to the pinned version that the current commit has baked in:

```
git submodule update --init --recursive
```

This command, on the other hand, causes all of the submodules of the current repository (recursively) to be updated to the very latest tip of the branch specified in `.gitmodules`, which is really dangerous - you may think you're testing with one dependency, when you're really testing with the very latest. It's like using `*` in your dependencies list instead of pinning a version:

```
git submodule update --init --recursive --remote
```

This PR removes all of the `--remote`s from `git submodule update` commands throughout the operator repository.

### CODE REVIEW

**Comment by danielpcox** [comment]
Tagging lots of people just for the FYI

**Comment by dontlaugh** [comment]
Good call :+1:

**Review by dontlaugh — APPROVED** [review]

**Review by joel-epstein — COMMENTED** [review]
This seems like a good idea.  Is it worth it to print a SHA to STDOUT?

**Comment by danielpcox** [comment]
`git submodule update` prints the SHA when it changes the branch, which I think is enough.

**Pull request merged**
