### PR TITLE
Remove priority class

### PR DESCRIPTION
**Pull request by joshuaswickirl**
See: OPS-26 https://greymatter.atlassian.net/browse/OPS-26

### CODE REVIEW

**Comment by alecholmez** [comment]
This will need a core patch as well: https://github.com/greymatter-io/greymatter-core/blob/main/k8s/outputs/controlensemble.cue#L42

Can we get that in first so the commits line up for all this stuff?

**Comment by joshuaswickirl** [comment]
Yeah that's here. https://github.com/greymatter-io/greymatter-core/pull/197

**Comment by joshuaswickirl** [comment]
> This will need a core patch as well: https://github.com/greymatter-io/greymatter-core/blob/main/k8s/outputs/controlensemble.cue#L42
> 
> Can we get that in first so the commits line up for all this stuff?

Yeah, here's the pr: https://github.com/greymatter-io/greymatter-core/pull/197

**Review by moosecanswim — APPROVED** [review]
LGTM.  Tho we dont really need to remove it from the operator since the operator will only create the resource if greymatter core specifies it.

**Review by alecholmez — APPROVED** [review]

**Comment by alecholmez** [comment]
I'd rather remove for now and then add back if a customer really needs this. Dead code = technical debt

**Pull request merged**
